### ISSUE TITLE
Move object and text attributes specs to this repository

### ISSUE THREAD

**Issue by jcsteh** [LinuxA11y/IAccessible2#24]
Follow up from #11.

The IAccessible2 text attributes specification is currently hosted on the Linux Foundation wiki. We should move it into this repository. This will probably involve converting it to Markdown.

CC @aleventhal.

**Comment by michaelweghorn** [comment]
Besides the [text attributes specification](https://wiki.linuxfoundation.org/accessibility/iaccessible2/textattributes), there's also the [object attributes spec](https://wiki.linuxfoundation.org/accessibility/iaccessible2/objectattributes) to consider for moving here.

**Comment by michaelweghorn** [comment]
I've submitted a PR for this: #27

Somewhat related to this: The IAccessible2 documentation hosted at https://accessibility.linuxfoundation.org/a11yspecs/ia2/docs/html/ is outdated. Is that just because there hasn't been any official release for a long time or does that also have to be moved somewhere else?

In case of the latter: Would it possibly make sense to automate this and always have a current version generated from git master? (I don't have any experience with this, but maybe Github pages might be a potential approach to implement that.)
